### ISSUE TITLE
Please add JARs for libraries

### ISSUE THREAD

**Issue by jbrucker** [keyboard2543/Perfect-Pitch#1]
For Opencsv and JMusic, if the jars are not too large
then please add them to a top-level directory named "lib".
This way others won't need to go download them.
But *do* include the list of dependencies and where to get them in README.md

src/  source code
lib/   libraries - not including JavaFX or anything > 2 MB.

**Comment by keyboard2543** [comment]
For Opencsv the jars is too large but JMusic is not. So I added JMusic. You can see lib and dependencies URLs within README.md .
